spring:
  application:
    name: bookshelfs
  mail:
    host:  ${MAIL_HOST}
    port:  ${MAIL_PORT}
    ssl:
      enabled: false
    username:  ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  thymeleaf:
    enabled: true
    check-template: true
    check-template-location: true
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    cache: false
  mvc:
    hidden-method:
      filter:
        enabled: true

app:
  base-url: ${BASE_URL}
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 часа

hcaptcha:
  secret: ${RECAPTCHA_SECRET:0x0000000000000000000000000000000000000000}
  site: ${RECAPTCHA_SITE:10000000-ffff-ffff-ffff-000000000001}

logging:
  level:
    io.petprojects.bookshelfs: DEBUG