spring:
  application:
    name: bookshelfs
  mail:
    host:  ${MAIL_HOST}
    port:  ${MAIL_PORT}
    ssl:
      enabled: false
    username:  ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


app:
  base-url: ${BASE_URL}
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24 часа

hcaptcha:
  secret: ${RECAPTCHA_SECRET:ES_d2e7f30776234e28923fbc73953a103b}
  site: ${RECAPTCHA_SITE:07f4e8d8-cce0-4b8e-9b4a-5004ec1a7c28}

logging:
  level:
    io.petprojects.bookshelfs: DEBUG